# Generated by Django 5.1.4 on 2025-01-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('url_or_path', models.CharField(max_length=2048)),
                ('new_tab', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Menu link',
                'verbose_name_plural': 'Menu links',
            },
        ),
    ]
